### ISSUE TITLE
log file of the upgrade process is in /tmp, so wiped on reboot.

### ISSUE THREAD

**Issue by stdevPavelmc** [skycoin/skywire-testnet#176]
The log of the upgrade process is on /tmp, so it's wiped on reboot.

That prevent the users to submit a log of a failed upgrade if they reboot their SBC.

**Comment by Asgaror** [comment]
Can we change log.txt to be dependent on the time/date? 
Like 
logfile_name = "log_$(date +%Y_%m_%d-%H:%M:%S)";
