### ISSUE TITLE
Nodes don't appear in manager web interface after updating

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire-testnet#180]
The redesigned UI version of the skywire manager page (latest update) nodes never show up as having connected to the manager.

The public keys of the nodes appear in the command output if the manager is started in the terminal without nohup.

The node keys check as running on skywirenc.com

An old instance of the manager shows nodes connecting in the web UI. The update did not affect the ability of nodes to connect, only of the manager receiving the connection and displaying it.

**Comment by stdevPavelmc** [comment]
Hi @0pcom you can join the [official Skywire Support Telegram channel](https://t.me/skywire) to get help. Please submit the upgrade logs here or there to analysis and better understanding of your status.

**Comment by 0pcom** [comment]
When I clear the browser cache I'm able to see newly connected nodes. Refreshing the page or clicking the refresh button does nothing.
