### ISSUE TITLE
Failed to initialise node; routing.db not found

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire-testnet#204]
#### OS/Distro: archlinux

After setting up [as directed in the mainnet readme](https://github.com/skycoin/skywire/blob/mainnet/README.md)

```
[user@host ~]$  skywire-node skywire.json
2019/03/05 19:00:01 Failed to initialise node: routing table: open ./skywire/routing.db: no such file or directory
[user@host ~]$
```

have a look at skywire.json

```
[user@host ~]$ printf '%b\n' "$(cat skywire.json)"
{
  "version": "1.0",
  "node": {
    "static_public_key": "02c721a37de52da1a0d36abc31efd6c6d0130232781e930eb54350dc84d5b6252d",
    "static_secret_key": "87d8ca3db77b771c8bffc719d35c863fe5e9c937203335b57ce9146247929eca"
  },
  "messaging": {
    "discovery": "https://messaging.discovery.skywire.skycoin.net",
    "server_count": 1
  },
  "transport": {
    "discovery": "https://transport.discovery.skywire.skycoin.net",
    "log_store": {
      "type": "file",
      "location": "./skywire/transport_logs"
    }
  },
  "routing": {
    "setup_nodes": [
      "0324579f003e6b4048bae2def4365e634d8e0e3054a20fc7af49daf2a179658557"
    ],
    "route_finder": "https://routefinder.skywire.skycoin.net/",
    "table": {
      "type": "boltdb",
      "location": "./skywire/routing.db"
    }
  },
  "apps": [
    {
      "version": "1.0",
      "app": "chat",
      "auto_start": true,
      "port": 1,
      "args": []
    },
    {
      "version": "1.0",
      "app": "therealssh",
      "auto_start": true,
      "port": 2,
      "args": []
    },
    {
      "version": "1.0",
      "app": "therealssh-client",
      "auto_start": true,
      "port": 22,
      "args": []
    },
    {
      "version": "1.0",
      "app": "therealproxy",
      "auto_start": true,
      "port": 3,
      "args": [
        "-passcode",
        "X9bgo9TCwFc="
      ]
    }
  ],
  "trusted_nodes": [],
  "manager_nodes": [],
  "apps_path": "./apps",
  "local_path": "./local",
  "log_level": "info",
  "interfaces": {
    "rpc": "localhost:3436"
  }
}
```

[https://routefinder.skywire.skycoin.net](https://routefinder.skywire.skycoin.net) serves a 404 page not found message; the same as one would see starting an instance of skywire-manager without correctly specifying `-web-dir`

The same page is displayed for
[https://transport.discovery.skywire.skycoin.net](https://transport.discovery.skywire.skycoin.net)
and
[https://messaging.discovery.skywire.skycoin.net](https://messaging.discovery.skywire.skycoin.net)

the `transport_logs` and the `routing.db` files don't exist anywhere I can find them; nor does the path `./skywire`

**Comment by ivcosla** [comment]
You have to manually create the directories "skywire" and "apps", as stated (here)[https://github.com/skycoin/skywire/blob/mainnet/README.md].

```bash
mkdir skywire
mkdir apps
```

After which it will be able to create `bolt.db`.

**Comment by evanlinjin** [comment]
This issue will can closed for now as it is invalid.

**Comment by 0pcom** [comment]
It only worked for me when I made the `skywire` directory permissions `777`

**Comment by ivcosla** [comment]
@0pcom this has been reported as working for other users without the need of giving all the permissions to the data directory. You have to provide a way for us to reproduce the issue.

**Comment by 0pcom** [comment]
@ivcosla my [PKGBUILD](https://github.com/0pcom/skycoin_archlinux_packages/blob/master/skywire-mainnet/PKGBUILD) creates the following setup:

* Binaries are placed in `/usr/lib/skycoin/go/bin`
* Binaries are symlinked to `/usr/bin`

run `skywire-cli config` and then `skywire-node skywire.json` from `~/` to reproduce this

If it were directory permissions, `skywire.json` would not be created. It is created, but `routing.db` is not, even if the path exists.
