### ISSUE TITLE
Decrease boltdb timeout on startup

### ISSUE THREAD

**Issue by Skvuddudutt** [skycoin/skywire-testnet#211]
On startup, the initial connection to the routing-db seems to never time out.

To reproduce, just start two skywire-node on the same machine configured to use the same boltdb-file. The second node will hang on startup.

**Comment by ayuryshev** [comment]
From https://github.com/etcd-io/bbolt#caveats--limitations:


"Bolt uses an exclusive write lock on the database file so it cannot be shared by multiple processes."

So it `wontfix`
