### ISSUE TITLE
Speed up lint and format process

### ISSUE THREAD

**Issue by ivcosla** [skycoin/skywire-testnet#213]
Both lint and format are way too slow right now, we have to check if there is a way to speed them up without loosing functionality.

**Comment by ayuryshev** [comment]
Is it still relevant?

**Comment by ivcosla** [comment]
Not important, but definitely slow right now.

**Comment by gz-c** [comment]
Linting can't be sped up if you're already using gometalinter.  Format isn't a problem if your editor autoformats as you save.
