### ISSUE TITLE
Inconsistency in  pkg/messaging/README.md#code-structure in mainnet branch

### ISSUE THREAD

**Issue by ayuryshev** [skycoin/skywire-testnet#215]
https://github.com/skycoin/skywire/blob/mainnet/pkg/messaging/README.md#code-structure

Expected `tree`-output (or filelist) of code-files but there are descriptions for inexistent files (maybe from previous releases)

**Comment by jdknives** [comment]
Can you make a PR that closes this issue and deletes said README.md? @ayuryshev

**Comment by ayuryshev** [comment]
We removed it already

**Comment by jdknives** [comment]
There was a commit to your Skywire fork, but it is still present in skycoin/skywire `mainnet`. https://github.com/skycoin/skywire/tree/mainnet/pkg/messaging

**Comment by jdknives** [comment]
Closed by #266
