### ISSUE TITLE
Create dev-environment with dockerized skywire-node

### ISSUE THREAD

**Issue by ayuryshev** [skycoin/skywire-testnet#218]
Create dev-environment with dockerized skywire-node

Automate them as Makefile-goals:
  Creation of node 
  Refresh-restart of node

Document changes

**Comment by jdknives** [comment]
@ayuryshev I guess this can be closed as well?

**Comment by jdknives** [comment]
@ayuryshev shall we close this for now?

**Comment by ayuryshev** [comment]
Done.
