### ISSUE TITLE
ACK failure upon many send operations

### ISSUE THREAD

**Issue by ivcosla** [skycoin/skywire-testnet#225]
I found this error by using chat app and writing many messages, eventually there is a CRC error within ACK: https://github.com/skycoin/skywire/blob/mainnet/internal/ioutil/ack.go#L194

Errors shown on both nodes:
Sender
![Captura de pantalla 2019-03-15 a las 10 56 31](https://user-images.githubusercontent.com/4092306/54432151-a7bdab80-4728-11e9-9205-588539a0af13.png)

Receiver
![Captura de pantalla 2019-03-15 a las 10 56 47](https://user-images.githubusercontent.com/4092306/54432175-b4da9a80-4728-11e9-8639-467989bacb33.png)

After such error it is impossible to keep using chat app.

**Comment by ivcosla** [comment]
@evanlinjin @jdknives 

After working in this for a while I don't see any obvious reason for ack's to fail other than corruption in the net package that carries the ack.

Currently, when this happens apps using such transport just hangs, and to work again they need to be restarted and transports to be re-created.

I think that it would be interesting to add some kind of "retry" to transports, or at least make the apps fail gracefully, so it is easy for the user to manually retry.

What do you think?

**Comment by jdknives** [comment]
We should create an issue that supersedes (and references) this issue and #221 in my opinion, that specifies what we suspect the actual issue is. A graceful shutdown could be valubale anyways in the meantime, while I think that retry logic is not needed for now as we need to fix the underlying corruption. @ivcosla

**Comment by jdknives** [comment]
Closed by #268
