### ISSUE TITLE
Create testify test-suite for chat application 

### ISSUE THREAD

**Issue by ayuryshev** [skycoin/skywire-testnet#233]
Create test-suite in cmd/apps/chat/chat_test.go using "testify"

- testify/suite - for startup and teardown
- testify/assert & testify/require for tests themself

Initial set of test-cases:
- Startup: start prepared 2 nodes
- add-transport to link them
- "Hello-Mike-Hello-Joe" 
- exchange of multiple single-letter messages
- exchange of multiple messages with increasing size
- Teardown: stop nodes

**Comment by evanlinjin** [comment]
@ayuryshev thanks for the ticket. Remeber to add the `mainnet` label to issues revolving around mainnet in the future. Thanks!

**Comment by jdknives** [comment]
@ayuryshev Steve requested that we do not use testify/suite. Please clean up the branch and close this issue.

**Comment by jdknives** [comment]
Closed by above comment.
