### ISSUE TITLE
Ensure travis makes proper use of vendor folder.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#234]
Currently, travis is downloading all dependencies even though we have a `vendor` folder.

## Resources
- https://arslan.io/2018/08/26/using-go-modules-with-vendor-support-on-travis-ci/

**Comment by gz-c** [comment]
Doesn't the `vendorcheck` tool check this?

**Comment by gz-c** [comment]
https://github.com/FiloSottile/vendorcheck

**Comment by gz-c** [comment]
`vendorcheck` is included in the `make lint` standards defined in: https://github.com/skycoin/skycoin/wiki/Skycoin-project-Makefile-standards#make-lint

I opened a new issue to have Skywire updated to the Makefile and travis standards: https://github.com/skycoin/skywire/issues/235
