### ISSUE TITLE
Create `skywire-cli pk` command.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#238]
I would prefer creating a sub-command within `skywire-cli` (for example `skywire-cli pk`), that retries the public key of the node.

_Originally posted by @evanlinjin in https://github.com/skycoin/skywire/pull/232_

**Comment by jdknives** [comment]
@ayuryshev this has been fixed by #243 , but you need to put the `close: xyz` into the initial comment of the PR.
