### ISSUE TITLE
Create go-fuzz tests for `conn.Write` in `pkg/app/conn`

### ISSUE THREAD

**Issue by ayuryshev** [skycoin/skywire-testnet#246]
Create `go-fuzz` tests for `conn.Write` in:

- https://github.com/skycoin/skywire/blob/4b910dc912d4691b47e6482f7e009cafd4eac907/pkg/app/conn.go#L69

**Comment by gz-c** [comment]
Whats the point of fuzzing writing to a socket?

**Comment by ayuryshev** [comment]
Agreed. It was not a well-thought idea
