### ISSUE TITLE
Transport removal doesn't work correctly

### ISSUE THREAD

**Issue by ivcosla** [skycoin/skywire-testnet#249]
Related to #248 .

After several transports appear by using apps, those transports can be removed by using `skywire-cli rm transport-id`, but after that, in some cases, new transports will be created after the remove operation.

In order to reproduce it:
1) follow steps in #248 .

2) Call `skywire-cli list-transports`

3) Start to manually remove transports from the above list by using `skywire rm-transport`

4) Call `skywire-cli list-transports` again, now you should be able to see that there are new transports with new ids

**Comment by jdknives** [comment]
Closed by #252
