### ISSUE TITLE
The command 'make lint' does not recursively check files in 'cmd' dir.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#258]
This results in `make lint` passing locally, but not in Travis.

**Comment by jdknives** [comment]
It seems like Travis runs `make check` which runs `make lint` as far as I can tell. Is this issue still valid? @evanlinjin

**Comment by evanlinjin** [comment]
> It seems like Travis runs `make check` which runs `make lint` as far as I can tell. Is this issue still valid? @evanlinjin

Whether Travis runs `make lint` via `make check` or not is irrelevant to this issue. The issue at hand is not that `make lint` is not run, but rather `make lint` does not have the correct behavior when running locally.

In regards to whether it is fixed, as we have not touched the `/cmd` folder for a while, so I cannot confirm, I'll check now. As I remember, @ayuryshev has fixed this.

**Comment by ayuryshev** [comment]
It would be very strange if `linter` in travis  would be so different from from desktop linuxes or even MacOS.

What I did  was "pinning" version of gometalinter and: 
- `make install-linters` in developer environment
-  and travis by ci_scripts
Installs the same version

I checked .golangci.yml and .travis - I don't see excluded or ignored files
