### ISSUE TITLE
Detect unstable tests

### ISSUE THREAD

**Issue by ayuryshev** [skycoin/skywire-testnet#280]
# Problem

It was observed that some tests fails randomly: for N starts they could fail M times.

# Task

Write script that:

- runs `go test` repeateadly for **every** test in system with big enough count of  iterations 
- collect statistics

From collected statistics:
- detect stable and unstable tests
- publish results

**Comment by gz-c** [comment]
running with the race detector on could find some quickly

**Comment by ayuryshev** [comment]
We found unstable tests without data races detectable by `go test -race`. 
First suspects are from pkg/messaging/client_test.go

And it looks more probable that timeouts came from incorrect acquire-release of resources, incorrect mutex lock/unlock than undetected data races.

**Comment by ayuryshev** [comment]
Done
