### ISSUE TITLE
Listing transports in `skywire-cli` should show if transport is used for setup node.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#335]
The current view looks as follows:
![image](https://user-images.githubusercontent.com/14065705/57370163-8dadc000-71e3-11e9-9e33-3cb9b83aae08.png)

We should have an additional column specifying the `mode-of-operation`: either `setup` or `regular`. (Open to suggestions for better naming conventions).

**Comment by jdknives** [comment]
Closed by #362
