### ISSUE TITLE
Data race in `chat` app

### ISSUE THREAD

**Issue by nkryuchkov** [skycoin/skywire-testnet#338]
https://github.com/skycoin/skywire/pull/337#issuecomment-490466077

Result from following test instructions from: https://github.com/ayuryshev/skywire-services/blob/feature/implement-integration-test-with-restart-cycle-62/integration/README.md#scenario-for-messaging-test-with-unstable-intermediary-skywire-node

![image](https://user-images.githubusercontent.com/24493220/57400835-12e1a680-71dd-11e9-8623-ade2a3e73833.png)

**Comment by ayuryshev** [comment]
Please add commit checksum for report

**Comment by atang152** [comment]
Hi. I was able to reproduce the above data-race error with the following steps:
1) Ran ./integration-run.sh
2) Wait until all services are up and ran ./integration/startup.sh
3) Ran n times the messaging-test script with:        for i in {1..100}; do "./integration/messaging-test.sh"; done
4) Open localhost:8000 with the browser --> This raises the Data Race error on 5:NodeA
5) Open localhost:8001 with the browser --> This raises the Data Race error on 7:NodeC

![Post_Test_DATA_RACE_startChatApp](https://user-images.githubusercontent.com/31387433/57440688-0b70da80-727b-11e9-9d97-e41b93739f09.png)

**Comment by evanlinjin** [comment]
Solved in #337
