### ISSUE TITLE
Cleanup: Avoid using the 'unsafe' package in 'messaging.channel'.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#348]
I think we should try to avoid using the `unsafe` package. What if we either use `atomic.Value` data type or `(u)int32` here? I would use `uint32` as a boolean considering `0` as `false` and any non-`0` value as `true`.

_Originally posted by @nkryuchkov in https://github.com/skycoin/skywire/pull/337_

**Comment by ayuryshev** [comment]
I see usage of `unsafe` only in one file: https://github.com/skycoin/skywire/blob/45110a5586423df2bec6b2c687e1b43630a83af7/pkg/messaging/channel.go

And here it used in combination with `sync.atomic`

And used as:
```golang
closed:    unsafe.Pointer(new(bool)), //nolint:gosec
```

Could this issue reformulated  as: "Cleanup: Change type of channel.closed from unsafe.Pointer to safe type" ?

**Comment by gz-c** [comment]
Likely that entire file needs its synchronization management to be redesigned.  But `unsafe` should definitely never be used.

**Comment by evanlinjin** [comment]
Fixed by #373 #369
