### ISSUE TITLE
Data races on exit of Skywire-nodes

### ISSUE THREAD

**Issue by ayuryshev** [skycoin/skywire-testnet#354]
# How to reproduce bug

1. Start 3 skywire-nodes: 
- NodeA with thereallssh app
- intermediary NodeB without apps
- NodeC with therealssh-client app
2. Add transports from NodeA and NodeC to NodeB
3. Start ssh communication. E.g. `therealssh-cli $PK_A "echo A"` (or `cat` a file, `ls`, `tree`, etc)
4. Kill nodes during proccess

With high probability data races will be on one or two of nodes.

Sometimes data race is followed with `panic: send on closed channel` and sometimes not.

Attached logs:
- nodeB.log and nodeC.log - are from one run
- nodeA.log - from another

[nodeC.log](https://github.com/skycoin/skywire/files/3186281/nodeC.log)
[nodeB.log](https://github.com/skycoin/skywire/files/3186282/nodeB.log)
[nodeA.log](https://github.com/skycoin/skywire/files/3186283/nodeA.log)

**Comment by gz-c** [comment]
How do i configure NodeA, NodeB, NodeC?

**Comment by jdknives** [comment]
Closed by #361
