### ISSUE TITLE
Corrected wiki page

### ISSUE THREAD

**Issue by mrtom31** [skycoin/skywire-testnet#360]
Correction of code in wiki page:
- Added a missing loop
- Changed @{HOSTNAME} by @${HOSTNAME}

Here is the [related page corrected](https://github.com/mrtom31/skywire/wiki/Automated-reboot-if-network-connection-drops)
[here is the difference to the old one](https://github.com/mrtom31/skywire/wiki/Automated-reboot-if-network-connection-drops/_compare/6b6d17ee3a066d3b1334de15cf6878defff4420c...87b7cc6ed84985740a1defd69d469dc5d9a9a9f5?diff=split)

**Comment by Asgaror** [comment]
Thanks for the heads up @mrtom31 

Fixed in https://github.com/skycoin/skywire/wiki/Automated-reboot-if-network-connection-drops/_compare/54928647589bbcf401cc8e6511215e1575031abe
