### ISSUE TITLE
Cleanup: Elimination of closing channels and copying data in Manager.Observe

### ISSUE THREAD

**Issue by ayuryshev** [skycoin/skywire-testnet#365]
# Analysis

```golang
func (tm *Manager) Observe() (accept <-chan *ManagedTransport, dial <-chan *ManagedTransport) {
	dialCh := make(chan *ManagedTransport)
	acceptCh := make(chan *ManagedTransport)
	go func() {
		for {
			select {
			case <-tm.doneChan:
				close(dialCh)
				close(acceptCh)
				return
			case tr := <-tm.acceptedTrChan:
				acceptCh <- tr
			case tr := <-tm.dialedTrChan:
				dialCh <- tr
			}
		}
	}()
	return tm.AcceptedTrChan, tm.DialedTrChan
}
```
Those `close(dialCh)` and `close(acceptCh)` are possible cause of `panic: send on closed channel` in  #354 

Copying data from `tm.acceptedTrChan` and `tm.dialedTrChan` looks dubious too. It's a possible source of more subtle errors.

# TODO 

Eliminate or justify existence of `close` instructions and copying data.

1. Remove dubious instructions
2. Test it
3. Publish results

**Comment by gz-c** [comment]
Is this code snippet the actual code?

**Comment by ayuryshev** [comment]
It was eliminated in https://github.com/skycoin/skywire/pull/366
No reason for existence of this lines was not found.

**Comment by jdknives** [comment]
@gz-c yes. That is actual code in `mainnet`.

**Comment by ayuryshev** [comment]
Done
