### ISSUE TITLE
Version info

### ISSUE THREAD

**Issue by mrhodlr** [skycoin/skywire-testnet#38]
I was trying to find a command line option to discover which version of the Skywire software was installed, and was unable to find one, or any way to check the version for that matter.

Should there be an easy way to check this?

skycoin -version
or
make ARGS=‘-version’ run

**Comment by vyloy** [comment]
It is planing to be added in the testnet release

**Comment by BigOokie** [comment]
Looking through the current source, it looks like the Skywire node app contains a version parameter (-v). Is this what you are looking for?

./node -v

This returns 0.1.0 for me at the moment.

**Comment by BigOokie** [comment]
Works for Skywire Manager also
./manager -v

**Comment by BigOokie** [comment]
Can this issue be closed? 
Both node and manager report their version when passed the ‘-v’ parameter at the command line

**Comment by gz-c** [comment]
If asking for skycoin, https://github.com/skycoin/skycoin/issues/1390
