### ISSUE TITLE
Broken pipe error while SSH-cli

### ISSUE THREAD

**Issue by Darkren** [skycoin/skywire-testnet#383]
This one happened while investigating the #356. Suppose that it should be handled first.

Steps to reproduce:

1. Start 3 nodes: A (with SSH), B (without apps), C (with SSH-client)
2. Setup transports from C to B, from A to B
3. Run simple SSH communication like: `SSH-client $PK_A "echo A"
4. Kill all the nodes
5. Stop all processes left and do everything from the start

**Comment by jdknives** [comment]
>Tried several times, wasn’t able to reproduce. Some bugs happen between env starts, but tear-down.sh fixes it. Probably I made a bad use of it before which led to the creation of this issue. 

Commented by @Darkren
