### ISSUE TITLE
Feature: implement integration tests with public skywire-services

### ISSUE THREAD

**Issue by ayuryshev** [skycoin/skywire-testnet#387]
**Feature description**

Implement integration tests for messaging, ssh and proxy using public skywire-services.

**Is your feature request related to a problem? Please describe.**

It was observed that majority of issues are on skywire-node level (not in some of skywire-services).
So it makes perfect sense to run integration tests with public skywire-services.

**Describe the solution you'd like**

Collection of bash-scripts that skywire-nodes  connected to each other with different app configuration.
Plus scripts that generate load.

**Describe alternatives you've considered**

Alternatives:

1. Integration tests written in golang with `os.exec` 

Pluses:
- more control than bash
- ability to run with `go test`
- ability to use everything testing framework provide
   
2. Integration tests written in golang with docker SDK

Extension for previous alternative with pluses:

- more portable
- ability to add traffic control between nodes
- centralized logging from dockerized nodes

**Additional context**

It's not clear how or is it reasonably achievable integration with travis-ci.

**Possible implementation**

The most simplest way seems to port existing integration tests scripts from skywire-services.

- [ ] messaging environment 
- [ ] ssh environment
- [ ] proxy environment
- [ ] generic environment combining all subsystems
- [ ] ability to run with `go test`

**Comment by evanlinjin** [comment]
We should probably use `os.Exec` as discussed.

**Comment by jdknives** [comment]
Closed by #393
