### ISSUE TITLE
Command to start node from README.md doesn't work correctly

### ISSUE THREAD

**Issue by mrhodlr** [skycoin/skywire-testnet#39]
If I try to start the node using the command from README.md, I get a bunch of errors and even though the node starts, the node manager interface is completely non-responsive.  I am unable to access Settings, Check Update, Reboot, or anything.

I have tried changing the discovery address to
139.162.66.24:5999-03844a5482328ed32cc82d85c0cfaeefd7ec2106986673576ccee0df67c43b116f
on the advice of Zhiyi Wang, but had similar results.  At this point, I cannot seem to get a properly functioning node using publicly available documentation.  If I cannot, then I assume that other users cannot as well.

Here is a dump of the output:

root@skypi:~/go/bin# ./node -connect-manager -manager-address :5998 -manager-web :8000 -discovery-address messenger.skycoin.net:5999-028667f86c17f1b4120c5bf1e58f276cbc1110a60e80b7dc8bf291c6bec9970e74 -address :5000 -web-port :6001
DEBU[0000] writeOP &factory.regWithKey{PublicKey:cipher.PubKey{0x3, 0x94, 0x90, 0xee, 0x14, 0x21, 0x14, 0x4, 0x3b, 0x93, 0xbc, 0x5d, 0x0, 0xb0, 0xb, 0x8d, 0x21, 0xe2, 0x78, 0x66, 0xee, 0x3c, 0x4, 0x49, 0x87, 0xd8, 0x83, 0x2f, 0xdd, 0xa7, 0x65, 0xde, 0xab}, Context:map[string]string(nil), Version:1}  app=messenger ctxId=1 type=tcp
DEBU[0000] writeOP &factory.regCheckSig{Sig:cipher.Sig{0x53, 0x5c, 0xe2, 0x8b, 0x9f, 0x13, 0x8f, 0x1c, 0x3d, 0xa8, 0xb6, 0x68, 0xaa, 0x6b, 0xab, 0xc6, 0x9, 0xb2, 0x32, 0x2c, 0x82, 0x92, 0xac, 0x20, 0x9d, 0x35, 0xf6, 0x85, 0x3f, 0x5e, 0xc3, 0x33, 0x77, 0xb0, 0xf7, 0x26, 0xf1, 0xbb, 0x16, 0x16, 0x24, 0xd9, 0x50, 0xba, 0x7, 0x1f, 0xc4, 0x7b, 0x13, 0x53, 0xd9, 0x8e, 0xb3, 0x75, 0xa4, 0x2f, 0x93, 0xd0, 0x55, 0x14, 0x11, 0xc6, 0x9d, 0xca, 0x0}, Version:1}  app=messenger ctxId=1 type=tcp
DEBU[0000] listen on :5000
DEBU[0000] execute op &factory.regWithKeyResp{Num:[]uint8{0xf, 0x17, 0x85, 0xe3, 0x1, 0x40, 0xde, 0xdf, 0xea, 0x5b, 0x69, 0x6b, 0x4b, 0x4c, 0x6e, 0x82}, Hash:cipher.SHA256{0xc6, 0x55, 0xb6, 0x10, 0x73, 0x6b, 0x40, 0x9d, 0xf, 0xa4, 0xb5, 0xd, 0xd8, 0x34, 0x21, 0x70, 0xc6, 0x44, 0x3e, 0xfe, 0xa3, 0x13, 0x5f, 0x9c, 0x14, 0x48, 0x16, 0xef, 0x24, 0xd7, 0xbb, 0xf1}, PublicKey:cipher.PubKey{0x2, 0x86, 0x67, 0xf8, 0x6c, 0x17, 0xf1, 0xb4, 0x12, 0xc, 0x5b, 0xf1, 0xe5, 0x8f, 0x27, 0x6c, 0xbc, 0x11, 0x10, 0xa6, 0xe, 0x80, 0xb7, 0xdc, 0x8b, 0xf2, 0x91, 0xc6, 0xbe, 0xc9, 0x97, 0xe, 0x74}, Version:1} err <nil>  app=messenger ctxId=1 type=tcp
DEBU[0000] writeOP &factory.regWithKey{PublicKey:cipher.PubKey{0x3, 0x94, 0x90, 0xee, 0x14, 0x21, 0x14, 0x4, 0x3b, 0x93, 0xbc, 0x5d, 0x0, 0xb0, 0xb, 0x8d, 0x21, 0xe2, 0x78, 0x66, 0xee, 0x3c, 0x4, 0x49, 0x87, 0xd8, 0x83, 0x2f, 0xdd, 0xa7, 0x65, 0xde, 0xab}, Context:map[string]string{"node-api":":6001"}, Version:1}  app=messenger ctxId=2 type=tcp
DEBU[0000] writeOP &factory.regCheckSig{Sig:cipher.Sig{0x28, 0x5d, 0x53, 0x2b, 0x8d, 0x5d, 0x3b, 0x8d, 0xd4, 0x13, 0x9, 0xbc, 0x19, 0x60, 0xf8, 0x7f, 0x4d, 0xb5, 0xe1, 0xb4, 0x80, 0xc0, 0xf6, 0xa1, 0x42, 0xe7, 0x31, 0xdc, 0x18, 0x8f, 0x1f, 0x53, 0x4c, 0x46, 0xc1, 0x83, 0x80, 0x24, 0x24, 0x13, 0xb8, 0x95, 0xf3, 0x4e, 0xb9, 0xf6, 0x9a, 0x40, 0x7b, 0x19, 0x72, 0x10, 0x23, 0x4f, 0x4a, 0x79, 0x86, 0x29, 0xac, 0x59, 0xd, 0x51, 0x92, 0x72, 0x1}, Version:1}  app=messenger ctxId=2 type=tcp
DEBU[0000] execute op &factory.regWithKeyResp{Num:[]uint8{0x94, 0x1d, 0x1d, 0x70, 0x52, 0xfb, 0x15, 0x8a, 0x98, 0x50, 0x53, 0x2, 0x9, 0xbb, 0x62, 0xc9}, Hash:cipher.SHA256{0xb1, 0xa, 0x54, 0x83, 0x52, 0x98, 0x39, 0x96, 0x4a, 0xa1, 0xd, 0xe1, 0x73, 0x58, 0xcd, 0xd1, 0xa3, 0x4c, 0xe2, 0xd2, 0x30, 0x2, 0x34, 0xde, 0x98, 0xb6, 0x99, 0x45, 0xa9, 0x93, 0x31, 0x97}, PublicKey:cipher.PubKey{0x3, 0x3d, 0xd5, 0x34, 0xf3, 0xc1, 0x54, 0xea, 0xf1, 0x67, 0x64, 0x7, 0xb8, 0x31, 0x48, 0x0, 0x86, 0xec, 0x1a, 0x32, 0x4, 0x46, 0xe5, 0x37, 0xc1, 0x78, 0x8c, 0x7c, 0x13, 0xd9, 0xb5, 0xc6, 0x20}, Version:1} err <nil>  app=messenger ctxId=2 type=tcp
DEBU[0000] http server listening on :6001
DEBU[0001] writeOP &factory.regWithKeyResp{Num:[]uint8{0xa5, 0x99, 0xaf, 0xc1, 0x58, 0x30, 0x27, 0xdb, 0x34, 0xfe, 0xec, 0x28, 0xb4, 0x4d, 0x8b, 0xa6}, Hash:cipher.SHA256{0xa9, 0x26, 0xd5, 0xff, 0x58, 0xa9, 0x7b, 0xfd, 0xd9, 0x4a, 0xd1, 0x63, 0x45, 0x10, 0x38, 0x36, 0x36, 0x43, 0x48, 0x2c, 0xf9, 0x30, 0xb8, 0x3b, 0x72, 0x43, 0x7, 0xdb, 0x13, 0x94, 0x74, 0xfb}, PublicKey:cipher.PubKey{0x3, 0x94, 0x90, 0xee, 0x14, 0x21, 0x14, 0x4, 0x3b, 0x93, 0xbc, 0x5d, 0x0, 0xb0, 0xb, 0x8d, 0x21, 0xe2, 0x78, 0x66, 0xee, 0x3c, 0x4, 0x49, 0x87, 0xd8, 0x83, 0x2f, 0xdd, 0xa7, 0x65, 0xde, 0xab}, Version:1}  app=messenger ctxId=3 type=tcp
DEBU[0001] reg 025acbff8340ecd506e77be7ca9bcd702f97396d183556671672e3cbb111bba8c3 0x4420274680
DEBU[0001] writeOP &factory.NodeServices{Services:[]*factory.Service{(*factory.Service)(0x4420395880)}, ServiceAddress:""}  app=messenger ctxId=1 type=tcp

**Comment by BoyangZhu** [comment]
I'm having the same issue.

**Comment by vyloy** [comment]
Hmmm, the log above is fine.
You can check http://messenger.skycoin.net:8999 to find out how many nodes connected.

Both 139.162.66.24:5999-03844a5482328ed32cc82d85c0cfaeefd7ec2106986673576ccee0df67c43b116f
And 
messenger.skycoin.net:5999-028667f86c17f1b4120c5bf1e58f276cbc1110a60e80b7dc8bf291c6bec9970e74
are just 1 cpu 1G linode vps for alpha testing.

It was oom killed several times.
`Mar  9 00:28:17 debian kernel: [ 1070]  1000  1070   271850   205725     521       6    43785             0 discovery
Mar  9 14:08:56 debian kernel: discovery invoked oom-killer: gfp_mask=0x14280ca(GFP_HIGHUSER_MOVABLE|__GFP_ZERO), nodemask=(null),  order=0, oom_score_adj=0
Mar  9 14:08:56 debian kernel: discovery cpuset=/ mems_allowed=0
Mar  9 14:08:56 debian kernel: CPU: 0 PID: 3919 Comm: discovery Not tainted 4.14.12-x86_64-linode92 #1
Mar  9 14:08:56 debian kernel: [ 3908]  1000  3908   268709   208400     510       6    39797             0 discovery
Mar  9 14:08:56 debian kernel: oom_reaper: reaped process 3908 (discovery), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB`

So we prepared more powerful servers for the coming testnet version.
13.113.87.139:5999-03264365136a1587f1df42aad0339a3c16d4ffa621d5b1892ceae3ab646482c00a

18.219.138.23:5999-029aa3b3adc1b3454304696aa8dd22bef3f59af07f75f948383fad365fe29b4053

And you can check how many nodes connected by accessing http port 8999, (like:http://13.113.87.139:8999, http://18.219.138.23:8999)

And as you can see, people are connected before our releasing, lol

**Comment by vyloy** [comment]
From the feedback, it is because browser was using some firewall/adblocker features.
