### ISSUE TITLE
Feature: make timeout delay for terminating apps configurable

### ISSUE THREAD

**Issue by ayuryshev** [skycoin/skywire-testnet#390]
**Description**

Make timeout delay for terminating apps configurable

**Explanation**

https://github.com/skycoin/skywire/blob/556f0d5deb25486d3b4fcac6d04b19a6739c2bf2/cmd/skywire-node/commands/root.go#L81

```golang
		ch := make(chan os.Signal, 2)
		signal.Notify(ch, []os.Signal{syscall.SIGINT, syscall.SIGTERM, syscall.SIGQUIT}...)
		<-ch
		go func() {
			select {
			case <-time.After(10 * time.Second):
				logger.Fatal("Timeout reached: terminating")
			case s := <-ch:
				logger.Fatalf("Received signal %s: terminating", s)
			}
		}()
```

Make predefined value `10 * time.Second` configurable in skywire-node config file.

**Comment by jdknives** [comment]
Closed by #396
