### ISSUE TITLE
Bug: Incorrect syslog hook in skywire-nod

### ISSUE THREAD

**Issue by ayuryshev** [skycoin/skywire-testnet#404]
**Describe the bug**

skywire-node creates logrus.Logger multiple times for every subsystem.

Hooks added by logging.AddHook in cmd/skywire-node/commands/root.go works only on upper level.

**Environment information:**

In every environment.

**Steps to Reproduce**

1. Run syslog-ng
2. Run skywire-node with --syslog param

E.g.
```bash
./skywire-node --syslog localhost:514 --tag NodeA
```

**Actual behavior**

Look at logs collected by syslog.
Notice that only logs from cmd/skywire-node/commands/root.go  were collected.

**Expected behavior**

Logs from all subsystems are expected.

**Additional context**

**Possible implementation**

Instead of `logging.MustGetLogger` each time in every package:

1. Create one `logging.NewMasterLogger` for skywire-node
2. Add hooks for MasterLogger
2. Create additional `PackageLogger` when needed

**Comment by jdknives** [comment]
Closed bz #416
