### ISSUE TITLE
Consider using maps instead of arrays within dmsg.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#419]
I would consider map here - exactly as in comment.
Performance here will be all eaten with network io and concurrency.

_Originally posted by @ayuryshev in https://github.com/skycoin/skywire/timeline_

**Comment by evanlinjin** [comment]
https://github.com/skycoin/skywire/pull/402#discussion_r295934850

**Comment by nkryuchkov** [comment]
Moved to https://github.com/skycoin/dmsg/issues/8
