### ISSUE TITLE
Improve dmsg tests.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#420]
The following are comments regarding `dmsg` test improvements. Do not consider then as the model implementation. But note that the queries need to be resolved in some form or another:

- [ ] https://github.com/skycoin/skywire/pull/402/files/81eee395f83803e10e8fb30d49790978f8215dee?file-filters%5B%5D=#r295770293

- [ ] https://github.com/skycoin/skywire/pull/402/files/81eee395f83803e10e8fb30d49790978f8215dee?file-filters%5B%5D=#r295770731

- [ ] https://github.com/skycoin/skywire/pull/402/files/81eee395f83803e10e8fb30d49790978f8215dee?file-filters%5B%5D=#r295776402

- [ ] https://github.com/skycoin/skywire/pull/402/files/81eee395f83803e10e8fb30d49790978f8215dee?file-filters%5B%5D=#r295778074

**Comment by nkryuchkov** [comment]
To be done:

- [ ] https://github.com/skycoin/skywire/pull/423#discussion_r297051269

**Comment by nkryuchkov** [comment]
Moved to https://github.com/skycoin/dmsg/issues/1
