### ISSUE TITLE
Feauture: transport.Factory+transport.Transport implementation as golang plugin

### ISSUE THREAD

**Issue by ayuryshev** [skycoin/skywire-testnet#425]
**Feature description**

Feauture: transport.Factory implementation as golang plugin

**Is your feature request related to a problem? Please describe.**

At the moment process of switching from `messaging` to `dmsg` is going.
It seems highly probable that it's not the last time.
Also ability to switch `transport.Factory` implementation without changes in skywire-node seems very desirable in future.

**Describe the solution you'd like**

1. Implementation of `transport.Factory`+`transport.Transport` as golang plugin 
2. Ability in skywire-node to load Factory&Transport plugin during startup
3. Ability to define in skywire-node configuration which plugin to use without need of recompilation.

**Describe alternatives you've considered**

**Additional context**

**Possible implementation**

Possible steps for implementation:

- [ ] Modify `node.Node` - make `messenger *dmsg.Client` into `transport.Factory`
- [ ] Modify `setup.Node` in the same way
- [ ] Modify messaging-server in the same way
- [ ] Define types for loadable plugins. I would look into [coredns](https://github.com/coredns/coredns/tree/master/plugin) code for inspiration
- [ ] Create dummy implementation of pluging and implement loading
- [ ] Transform dmsg package into plugin
- [ ] Test. Publish

**Comment by evanlinjin** [comment]
Golang plugin is interesting. However what is described as a problem here is not really a problem and golang plugin is not appropriate here, it's only going to add complexity.
