### ISSUE TITLE
Improve `dmsg` logging.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#426]
- [ ] Receiving a frame should be under `Debug`. Only connection and disconnection, of transports and remote services, should be under `Info`.
- [x] Tests should have logging set to "error".

**Comment by ayuryshev** [comment]
>> Test should have logging set to "error"
It's already accomplished in https://github.com/skycoin/skywire/pull/416 on global level

**Comment by jdknives** [comment]
@ayuryshev If you could please remove the merge conflicts from #416 , we could merge that PR. :+1

**Comment by nkryuchkov** [comment]
Moved to https://github.com/skycoin/dmsg/issues/10
