### ISSUE TITLE
First messages after route creation is lost

### ISSUE THREAD

**Issue by ivcosla** [skycoin/skywire-testnet#428]
In an scenario of A -> B -> C where A and C run apps and B behaves as an intermediary node between them, after A tries to send a message to C using `skychat` app a route is stablished to connect A to C thru B.

After such route is stablished the first message between them is lost. You can check this by going into `localhost:8000` (A's skychat app) and `localhost:8001` (C's skychat app) and sending a message from one to another. You should see that the first or two first messages that you send don't make it to the other end. 

Further messages will be delivered and from there on they work correctly.

Attached are the logs of each one of those nodes:
[A.log](https://github.com/skycoin/skywire/files/3324677/A.log)
[B.log](https://github.com/skycoin/skywire/files/3324678/B.log)
[C.log](https://github.com/skycoin/skywire/files/3324679/C.log)

**Comment by Darkren** [comment]
Tried this, was not able to reproduce. This one probably needs more attention from others

**Comment by ayuryshev** [comment]
I was not able to reproduce this issue too.
```bash
./integration-run-messaging-env.sh
./integration-test-messaging.sh
```
First message take a long time but I see it NodeC logs that it arrived.

**Comment by jdknives** [comment]
@ivcosla maybe give it another clean test run then.

**Comment by ivcosla** [comment]
It doesn't seems present anymore
