### ISSUE TITLE
[ROUTING] Decouple 'managedTransport' from 'transport.Manager'.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#443]
**Summary:**
- Rename `transport.managedTransport` to `transport.managedDataTp` (as we will need `transport.managedSetupTp` in the future).
- `transport.managedDataTp` should be self-sufficient, and shouldn't depend on `transport.Manager` for restarts.

**Motivation:**
- Have `transport.managedDataTp` be fully responsible for re-establishment.
- Have transport establishment/reestablishment function in a more predictable manner.

## Changes

**In regard to Transport IDs:**
- Transport IDs should be derived from local/remote public keys and the transport type ONLY. Private data transports are not to be registered.
- The least-significant edge should ALWAYS be the initiator.
- The least-significant edge is responsible for re-establishing the transport.
- Maybe using the `big` module to determine least-significant edge will be simpler.

**Regarding the Settlement Handshake:**
- `managedDataTp` should be responsible for performing the settlement handshake.
- Only data-transports are required to register themselves in `transport.Discovery`.

**Regarding Read/Write operations:**
- Any failure to a transport's read/write should close the associated route (in which the read/write failed).

**Regarding data-transport logging:**
- We also need to remove read/write log chans. Records of read/write should be to a stored `big.Int` value (protected by mutex), and saved to disc in given intervals. The motivation for this is that with the current implementation, the `readLogChan` and `writeLogChan` is not closed, leading to memory leak.

**Regarding `transport.Manager` changes:**
- We should have two maps of `managedDataTp`s: `map[uuid.UUID]*managedDataTp` and `map[cipher.Pubkey]*managedDataTp`.
- The aforementioned maps should be filled with saved transports on startup (even though we haven't actually connected).
- Transports that are not data-transports do not need to be stored (for now).

**Comment by evanlinjin** [comment]
This ticket needs to be split into multiple tickets. I'm in the process of that now.

**Comment by jdknives** [comment]
@evanlinjin this is fixed by #508 ? If so please close it, if not lets discuss, whether this is relevant for the next Milestone.
