### ISSUE TITLE
[ROUTING] Data type cleanup.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#444]
We are using similar data types that can be combined to simplify procedures. The following is not a fully formulated list and someone needs to dive into the code to see what we can combine.

From my understanding:
- We were hiding the local node's public key from the apps (this was a pointless decision). Instead, we can just have a unified `Loop` structure that is used at all levels of the protocol.

**TODO: Finish formulating this ticket.**

**Comment by Darkren** [comment]
@evanlinjin could you please explain this a bit? Based on your description I understood that there are several data types inside `routing` which are very similair and may be combined to a single type. Is that what this discussion is about? I actually would be glad if you could please point me to a struct similair to each other. I didn't find such examples in `routing`, maybe I do not fully get your thought on this

**Comment by evanlinjin** [comment]
The following structures can be combined in some way or another, in my opinion:
https://github.com/skycoin/skywire/blob/9b8d26b4ffc3d9a19353c2e331ab38ecc012a23f/pkg/app/packet.go#L10-L13
https://github.com/skycoin/skywire/blob/9b8d26b4ffc3d9a19353c2e331ab38ecc012a23f/pkg/app/packet.go#L25-L28
https://github.com/skycoin/skywire/blob/9b8d26b4ffc3d9a19353c2e331ab38ecc012a23f/pkg/setup/protocol.go#L58-L64
https://github.com/skycoin/skywire/blob/9b8d26b4ffc3d9a19353c2e331ab38ecc012a23f/pkg/routing/loop.go#L11-L18

**Comment by evanlinjin** [comment]
1. `app.Addr` and `app.LoopAddr` can be combined and moved into `routing`.
2. `setup.LoopData` can make use of two `routing.Addr` (instead of `RemotePK`, `RemotePort`, `LocalPort`. It should also be renamed, and moved; `routing.LoopData`.
3. `routing.Loop` should also make use of `routing.Addr` instead of `LocalPort`/`RemotePort`.

**Comment by jdknives** [comment]
Closedby #482
