### ISSUE TITLE
Renaming to (hyper)visor

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire-testnet#452]
It was observed that Synth uses the words visor and hypervisor for what is now referred to as App Node (or node in code) and Manger Node. 

- [x] rename node to visor

- [x] rename manager node to hypervisor

**Comment by nkryuchkov** [comment]
Should the API routes be changed from `/nodes` to `/visors`?

**Comment by jdknives** [comment]
Closed by #458 and associated PR in skywire services.
