### ISSUE TITLE
Include more errors into lint check

### ISSUE THREAD

**Issue by Darkren** [skycoin/skywire-testnet#460]
I see that we have `- Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked` in the linter config. 

Although I understand that some of the errors are unlikely to ever happen, I suggest that we remove this or at least include some of its parts and modify the code to be more robust in case of such unexpected scenarios. Such an approach leads to heavy error ignoring all around the code (my concern arised when I took a look at `therealssh` code)

**Comment by nkryuchkov** [comment]
I fully agree with this. I think all errors should be explicitly handled even if they are very unlikely to happen.

**Comment by ivcosla** [comment]
I agree too

**Comment by jdknives** [comment]
This has been solved by above PRs.
