### ISSUE TITLE
[ROUTING] Remove encryption from routes.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#463]
Looking at how Brandon intends on how routes should function, doing encryption in the manner that we currently are, does not make sense.

Removing encryption from routes will also simplify the codebase.

**Comment by ayuryshev** [comment]
@evanlinjin Can you explain a little further "Removing encryption from routes" with links to code where encryption occurs and which is unnnecessary?
Thank you.
