### ISSUE TITLE
[ROUTING] Changes to transport.Transport interface.

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/skywire-testnet#469]
**The current problem**

The ability to differentiate between local/remote edges is very important when we use `transport.Transport`. The current solution of using `transport.Edges()` method is not elegant and results in additional boilerplate.

**Tasks**
- [ ] Replace `Edges() [2]cipher.PubKey` with `LocalPK() cipher.Pubkey` and `RemotePK() cipher.Pubkey` in `transport.Transport` definition.
- [ ] Improve methods that regards determining transport ID.

**Comment by evanlinjin** [comment]
@nkryuchkov Remember to link your PR here when you start on this :)

**Comment by nkryuchkov** [comment]
@evanlinjin Thanks for pointing out :) Actually, I've already started, so probably a good idea to create a WIP PR.
