### ISSUE TITLE
Update Skywire Readme with web-port info

### ISSUE THREAD

**Issue by BigOokie** [skycoin/skywire-testnet#47]
The Skywire Readme file contains a cmd line for running the Node, but there is no explanation about the ‘-web-port’ cmd line parameter.

From discussions in the Skywire telegram group sounds like most people are running the Node cmd verbatim and just changing the Manager IP.

If running multiple Nodes behind a firewall, each must have a seperate ‘-web-port’ set.

For example, set it to
‘:6001’ for node 1
‘:6002’ for node 2
Etc.

Can we get the Readme updated with details of this parameter and recommendations for multiple nodes

**Comment by BigOokie** [comment]
After further review of the code, it looks like the -web-port cmd line parameter is actually used for the API used by the Node.

I believe the -address parameter (defaulting to 5000) is used for node to listen on.

When running multiple nodes behind a router - won’t each node need to run on a different port (5000, 5001, etc) to allow them to work correctly with NAT firewall?

**Comment by vyloy** [comment]
-web-port is the api address which is used for `manager` to call, so manager can controls the nodes.
-address is used for `app` to connect to.

both of them are working inside skyminer, no need to expose to outside.

**Comment by BigOokie** [comment]
Thanks for the update. I will circulate the info in the Telegram group as there were a lot of questions about this.

**Comment by BigOokie** [comment]
Happy for you guys to close this issue.
