### ISSUE TITLE
Some links (anchors) in README.md are broken

### ISSUE THREAD

**Issue by nkryuchkov** [skycoin/skywire-testnet#477]
Examples:
- `Skywire Mainnet - Public Test Phase` -> `Running skywire in docker containers` -> `Customization of dockers` -> `1. DOCKER_IMAGE`
- `Skywire Mainnet - Public Test Phase` -> `Running skywire in docker containers` -> `Dockerized skywire-node recipes` -> `6. "Hello-Mike-Hello-Joe" test`

**Comment by jdknives** [comment]
Closed by #478
