### ISSUE TITLE
Proposal: Add Git hooks for doing `make dep`

### ISSUE THREAD

**Issue by nkryuchkov** [skycoin/skywire-testnet#492]
It's easy to forget to do `make dep` before every push and it's hard to review the `vendor` folder in a pull request. This may lead to the case when the code in the `master`/`mainnet` branch is broken. Therefore, I'd like to propose adding to our repositories Git `pre-commit` or `update` hooks that update the `vendor` folder

**Comment by therealssj** [comment]
wouldnt this slowdown things a lot?
doing `make dep` before every commit would turn annoying very quick imo

**Comment by nkryuchkov** [comment]
@therealssj On my laptop it takes about 5-7 seconds, which is not very long for me. But you're right that it may be annoying for someone else. I think that doing it every push is more preferred than every commit.

**Comment by therealssj** [comment]
maybe add PR template and in that add a question something like "was dep updated?"  or something along those lines

**Comment by nkryuchkov** [comment]
@therealssj I'm not sure if it solves the problem. Sometimes dep is updated when a PR is created but it becomes outdated after making some requested changes to the PR.

**Comment by ivcosla** [comment]
I think that is worth to wait a bit for it. If is something we need, it doesn't really matter if it is annoying.

**Comment by therealssj** [comment]
maybe create a shell script which does `make dep` and then checks for changes in vendor folder then add that as a travis check

**Comment by nkryuchkov** [comment]
@therealssj Sounds interesting. I think it might be a good solution.

**Comment by evanlinjin** [comment]
@nkryuchkov I think this is a good idea, however the problem specified is not the problem that we are met with.

From my understanding, `go mod download` or `go mod vendor` does not automatically update the dependencies to the latest versions. This behavior is put in place so that running `go mod vendor/download` does not break the code.

After we make updates to packages (such as `dmsg`), we need to remember to run `go get`. There is no workaround for this.

**Comment by jdknives** [comment]
@nkryuchkov do you agree with Evan? If so, please close this issue.

**Comment by nkryuchkov** [comment]
@jdknives Yes, I agree. 
@evanlinjin Thank you for the explanation.
