### ISSUE TITLE
[ROUTING] Integration env won't work

### ISSUE THREAD

**Issue by Darkren** [skycoin/skywire-testnet#531]
For now integration tests are constantly failing with the `Error while reading from Writer: bufio.Scanner: token too long` error. Error persists for all apps on `mainnet-milestone1` branches. To reproduce, simple run the env and start any test. For example:

1. `make integration-build`
2. `make integration-run-generic`
3. `./integration/startup.sh`
4. run test for any app

**Comment by nkryuchkov** [comment]
There's also panic on one of the nodes:

```
[2019-08-27T11:33:57+03:00] INFO [snet.dmsgC]: (HANDSHAKE) Accepted by remote. remote=02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1:36
[2019-08-27T11:33:57+03:00] INFO [snet.dmsgC]: Injected [ACK] received=<type:ACK><id:56958><size:2><seq:14174> remoteClient=02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1:36
[2019-08-27T11:33:57+03:00] INFO [snet.dmsgC]: (HANDSHAKE) Accepted locally. remote=02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1:~
[2019-08-27T11:33:57+03:00] INFO [snet.dmsgC]: Accepted [REQUEST] received=<type:REQUEST><id:56031><size:184> remoteClient=02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1 remoteServer=035915c609f71d0c7df27df85e
c698ceca0cb262590a54f732e3bbd0cc68d89282
[2019-08-27T11:33:57+03:00] INFO [snet.dmsgC]: Injected [FWD] bufSize="7/65535" received=<type:FWD><id:56031><size:9><seq:36741> remoteClient=02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1:~
[2019-08-27T11:33:57+03:00] INFO [route_manager]: handling setup request: setupPK(02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1)
[2019-08-27T11:33:57+03:00] INFO [route_manager]: Got new Setup request with type RequestRouteID
[2019-08-27T11:33:57+03:00] INFO [snet.dmsgC]: Injected [ACK] received=<type:ACK><id:56031><size:2><seq:51378> remoteClient=02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1:~
[2019-08-27T11:33:57+03:00] INFO [route_manager]: successfully handled setup request: setupPK(02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1)
panic: runtime error: index out of range

goroutine 71 [running]:
encoding/binary.bigEndian.Uint64(...)
        /usr/local/Cellar/go/1.12.9/libexec/src/encoding/binary/binary.go:124
github.com/skycoin/skywire/pkg/routing.Rule.Expiry(0x2ffc0ef, 0x0, 0x0, 0x2ffc0eb, 0xc0004437a8, 0xc0004437b0)
        /Users/nkryuchkov/GolandProjects/skywire/pkg/routing/rule.go:46 +0x1e3
github.com/skycoin/skywire/pkg/router.(*managedRoutingTable).Cleanup.func1(0x9, 0x2ffc0ef, 0x0, 0x0, 0xc000443701)
        /Users/nkryuchkov/GolandProjects/skywire/pkg/router/managed_routing_table.go:37 +0x90
github.com/skycoin/skywire/pkg/routing.(*boltDBRoutingTable).RangeRules.func1.1(0x2ffc0eb, 0x4, 0x4, 0x2ffc0ef, 0x0, 0x0, 0x0, 0x0)
        /Users/nkryuchkov/GolandProjects/skywire/pkg/routing/boltdb_routing_table.go:88 +0x118
go.etcd.io/bbolt.(*Bucket).ForEach(0xc000099b40, 0xc00042c6e0, 0x7, 0x7)
        /Users/nkryuchkov/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/bucket.go:388 +0x1cc
github.com/skycoin/skywire/pkg/routing.(*boltDBRoutingTable).RangeRules.func1(0xc0003c81c0, 0x1935978, 0xc0003c81c0)
        /Users/nkryuchkov/GolandProjects/skywire/pkg/routing/boltdb_routing_table.go:94 +0x10a
go.etcd.io/bbolt.(*DB).View(0xc000108a00, 0xc00004ee50, 0x0, 0x0)
        /Users/nkryuchkov/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:725 +0xb7
github.com/skycoin/skywire/pkg/routing.(*boltDBRoutingTable).RangeRules(0xc00009e208, 0xc000443760, 0x0, 0x1fa2c28)
        /Users/nkryuchkov/GolandProjects/skywire/pkg/routing/boltdb_routing_table.go:85 +0x78
github.com/skycoin/skywire/pkg/router.(*managedRoutingTable).Cleanup(0xc0001aab40, 0xc00004ef40, 0x2)
        /Users/nkryuchkov/GolandProjects/skywire/pkg/router/managed_routing_table.go:36 +0x18a
github.com/skycoin/skywire/pkg/router.(*routeManager).rtGarbageCollectLoop(0xc0000a0840)
        /Users/nkryuchkov/GolandProjects/skywire/pkg/router/route_manager.go:146 +0x1d9
created by github.com/skycoin/skywire/pkg/router.(*routeManager).Serve
        /Users/nkryuchkov/GolandProjects/skywire/pkg/router/route_manager.go:70 +0x51
```

**Comment by evanlinjin** [comment]
> There's also panic on one of the nodes:
> 
> ```
> [2019-08-27T11:33:57+03:00] INFO [snet.dmsgC]: (HANDSHAKE) Accepted by remote. remote=02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1:36
> [2019-08-27T11:33:57+03:00] INFO [snet.dmsgC]: Injected [ACK] received=<type:ACK><id:56958><size:2><seq:14174> remoteClient=02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1:36
> [2019-08-27T11:33:57+03:00] INFO [snet.dmsgC]: (HANDSHAKE) Accepted locally. remote=02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1:~
> [2019-08-27T11:33:57+03:00] INFO [snet.dmsgC]: Accepted [REQUEST] received=<type:REQUEST><id:56031><size:184> remoteClient=02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1 remoteServer=035915c609f71d0c7df27df85e
> c698ceca0cb262590a54f732e3bbd0cc68d89282
> [2019-08-27T11:33:57+03:00] INFO [snet.dmsgC]: Injected [FWD] bufSize="7/65535" received=<type:FWD><id:56031><size:9><seq:36741> remoteClient=02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1:~
> [2019-08-27T11:33:57+03:00] INFO [route_manager]: handling setup request: setupPK(02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1)
> [2019-08-27T11:33:57+03:00] INFO [route_manager]: Got new Setup request with type RequestRouteID
> [2019-08-27T11:33:57+03:00] INFO [snet.dmsgC]: Injected [ACK] received=<type:ACK><id:56031><size:2><seq:51378> remoteClient=02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1:~
> [2019-08-27T11:33:57+03:00] INFO [route_manager]: successfully handled setup request: setupPK(02603d53d49b6575a0b8cee05b70dd23c86e42cd6cba99af769d61a6196ea2bcb1)
> panic: runtime error: index out of range
> 
> goroutine 71 [running]:
> encoding/binary.bigEndian.Uint64(...)
>         /usr/local/Cellar/go/1.12.9/libexec/src/encoding/binary/binary.go:124
> github.com/skycoin/skywire/pkg/routing.Rule.Expiry(0x2ffc0ef, 0x0, 0x0, 0x2ffc0eb, 0xc0004437a8, 0xc0004437b0)
>         /Users/nkryuchkov/GolandProjects/skywire/pkg/routing/rule.go:46 +0x1e3
> github.com/skycoin/skywire/pkg/router.(*managedRoutingTable).Cleanup.func1(0x9, 0x2ffc0ef, 0x0, 0x0, 0xc000443701)
>         /Users/nkryuchkov/GolandProjects/skywire/pkg/router/managed_routing_table.go:37 +0x90
> github.com/skycoin/skywire/pkg/routing.(*boltDBRoutingTable).RangeRules.func1.1(0x2ffc0eb, 0x4, 0x4, 0x2ffc0ef, 0x0, 0x0, 0x0, 0x0)
>         /Users/nkryuchkov/GolandProjects/skywire/pkg/routing/boltdb_routing_table.go:88 +0x118
> go.etcd.io/bbolt.(*Bucket).ForEach(0xc000099b40, 0xc00042c6e0, 0x7, 0x7)
>         /Users/nkryuchkov/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/bucket.go:388 +0x1cc
> github.com/skycoin/skywire/pkg/routing.(*boltDBRoutingTable).RangeRules.func1(0xc0003c81c0, 0x1935978, 0xc0003c81c0)
>         /Users/nkryuchkov/GolandProjects/skywire/pkg/routing/boltdb_routing_table.go:94 +0x10a
> go.etcd.io/bbolt.(*DB).View(0xc000108a00, 0xc00004ee50, 0x0, 0x0)
>         /Users/nkryuchkov/go/pkg/mod/go.etcd.io/bbolt@v1.3.3/db.go:725 +0xb7
> github.com/skycoin/skywire/pkg/routing.(*boltDBRoutingTable).RangeRules(0xc00009e208, 0xc000443760, 0x0, 0x1fa2c28)
>         /Users/nkryuchkov/GolandProjects/skywire/pkg/routing/boltdb_routing_table.go:85 +0x78
> github.com/skycoin/skywire/pkg/router.(*managedRoutingTable).Cleanup(0xc0001aab40, 0xc00004ef40, 0x2)
>         /Users/nkryuchkov/GolandProjects/skywire/pkg/router/managed_routing_table.go:36 +0x18a
> github.com/skycoin/skywire/pkg/router.(*routeManager).rtGarbageCollectLoop(0xc0000a0840)
>         /Users/nkryuchkov/GolandProjects/skywire/pkg/router/route_manager.go:146 +0x1d9
> created by github.com/skycoin/skywire/pkg/router.(*routeManager).Serve
>         /Users/nkryuchkov/GolandProjects/skywire/pkg/router/route_manager.go:70 +0x51
> ```

@Darkren I thought you fixed this at some point?

**Comment by Darkren** [comment]
@evanlinjin I fixed it manually without commiting anything during work on my own branch just to see whether new error appears or not. Fix for this is to find the `occupyRouteID` func and instead of `nil` put into the table `routing.ForwardRule(RouteTTL, other_default_values)`
