### ISSUE TITLE
[M2] Implement router2 according to specs

### ISSUE THREAD

**Issue by Darkren** [skycoin/skywire-testnet#545]
The goal is to split out and define the responsiblities within `router` to allow for easier integration of future features, as well as make the codebase easier to understand.

**Specifications:** https://github.com/watercompany/skywire-specs/blob/master/proposals/router2.md

**Comment by nkryuchkov** [comment]
Replaced by https://github.com/SkycoinProject/skywire-mainnet/issues/50
