### ISSUE TITLE
Skywire Manager Glitching out:

### ISSUE THREAD

**Issue by ADepic** [skycoin/skywire-testnet#55]
I connect to raspberry pi using ssh and enter these two commands:

nohup ./manager -web-dir ${GOPATH}/src/github.com/skycoin/skywire/static/skywire-manager > /dev/null 2>&1 & echo $! > manager.pid

nohup ./node -connect-manager -manager-address 192.168.1.1:5998 -manager-web 192.186.1.1:8000 > /dev/null 2>&1 & echo $! > node.pid

And then launch manager at the local ip address for the raspberry pi.

However when I click on the option of "Check Update", "Settings" , "Connect to node" or "Connect to node > Search Services", the pop-up that appears just dissapears.

With Terminal, I can get a glimpse of a error coming up:
![bad_handshake](https://user-images.githubusercontent.com/24532838/39971394-c7d1a852-56e9-11e8-985c-243a25f918f9.png)

And with reboot, the warning sign comes up, I press "Yes", and then: 
"Error
manager token is null"

I suddenly got this problem after a reboot. I was messing around with some sh scripts.

**Comment by nikogabs** [comment]
Hello
After, 13 hours online, i had the same issue whith all my nodes, impossible to contact them via the manager terminal and i got exactly the same error as above. Idem for the reboot button.
I reboot all my nodes and everything is back up.
