### ISSUE TITLE
current images don't work; issues updating old images

### ISSUE THREAD

**Issue by 0pcom** [skycoin/skywire-testnet#85]
the current (6/26/18) manager and node image downloads don't seem to want to work.

There is brief signal over HDMI but no text is displayed.
RED and GREEN LEDs both stay lit.

After digging out the backup images from an earlier flash I attempted to update...

git init
git remote add origin https://github.com/skycoin/skywire.git
git remote set-url origin https://github.com/skycoin/skywire.git
cd $GOPATH/src/github.com/skycoin/skywire
git reset --hard
git clean -f -d
git pull origin master

^at this point, I get:  server certificate verification failed

ok i figured out it was from the wrong time.

hopefully, working images will be added soon.
the instructions should be updated to include:

git init 
git remote add origin

before git remote set-url.

instructions for setting the time and date would also be nice to include:

https://wiki.debian.org/DateTime#Set_the_time_manually
date --set

**Comment by mboeru** [comment]
Use the ntp part from this tutorial https://github.com/skycoin/skywire/wiki/Tunnel-all-exit-node-traffic-through-a-singular-vpn-connection

That will fix the ssl issues as well.

**Comment by 0pcom** [comment]
when i finished updating everything and checked 127.0.0.1:8000,
the manager was running but the nodes never autostarted.

when i reflashed the SD cards, i restored the keys to:
/root/.skywire/node/keys.json

after reflashing these, booting once, and then replacing keys.json - here are the exact series of commands I ran on each:

apt-get update
apt-get upgrade
date --set 2018-06-26
date --set 21:30:00
git init
git remote add origin https://github.com/skycoin/skywire.git
git remote set-url origin https://github.com/skycoin/skywire.git
cd $GOPATH/src/github.com/skycoin/skywire
git reset --hard
git clean -f -d
git pull origin master
go install -v ./...

Without updated, working images or the correct update commands I'm at a loss for what to do on this.

I have this official skywire #325 and also two others using different hardware.

Those other 2 were working but there keeps being brief power outages and i don't have autostart set up on the other hardware, so I have to manually start all of the nodes; which can take an hour or more. I was hoping to figure out the autostart from a closer examination of the official images, but as I've said I can't get these to work.

**Comment by 0pcom** [comment]
The message I got from support@skycoin.net indicated that the current images don't output on HDMI.

upon further investigation, I discovered and replaced a board that had bad ram / preformed inconsistent checksums on images. This required me to disassemble the unit and check every board for good measure.

A complaint that my associate and I have talked about on the mechanical end is that the HDMI access is blocked for the lower boards. The whole thing could and should have a rack mount variation, and as much as I do like that little aluminum box, I have dropped enough of those little plastic spacers on the ground by now from disassembling it that I haven't attempted to re-mount it yet, bu at least it is now working. I assume it is working, but I can't log into the manager. For now I am crossing my fingers.

Reconfigured, these eight boards could ft nicely in 3U of rack space with clean access to all USB and HDMI ports.

The new issue for me: how ssh to these boards since now there is no video output from the current images.

I know the answer is in the wiki link above, so thanks to mboeru and I'm going to close this issue

STILL: there is something strange about the command to 'stay up to date' on the official images. I hope someone will check this out as I think the commands are not quite everything you need, and I messed up my old images in the first place by trying to update them as instructed.
