### ISSUE TITLE
Node app/SSHS app disappear from UI after Skywire web process "manager" restarts

### ISSUE THREAD

**Issue by asxtree** [skycoin/skywire-testnet#90]
Hi,

I've encountered this Web UI bug which happens when the Skywire web process "skywire-manager" restarts.

**The Behavior** is that the node app or sshs app from all nodes seen in the manager Web UI simply disappears if the `manager` process restarts or is stopped and started again, although if i check via cli on the nodes, both processes (`sockss` and `sshs`) are running. 

**The Workaround** is to restart the `node` process.

!!!!!See the attached photo!!!!

![image](https://user-images.githubusercontent.com/34941232/42532009-2b093030-848e-11e8-99e1-dc62d51d4c9f.png)

**Comment by mrhodlr** [comment]
I have seen this many times as well, but there is more going on than just the Node App disappearing. When you reboot the manager, all nodes seem to lose part of their connection to manager, They still display but all the buttons in the UI become non-responsive.  Terminal window will not open, you cannot click on Settings to check or update Discovery Address, if you click on the Reboot button you get the error message "Manager Token Null"

**Comment by some4** [comment]
I've been trying to isolate this from the system side and would like to add an observation.

Skywire and GOPATH/GOBIN in `/home/$user/`:

If I run Node and Manager as:

- $user: the `.skywire` directory is created in `/home/$user/`

- root: the `.skywire` directory is created in `/home/$user/go/bin/`

What led me to this is I've been following: https://github.com/skycoin/skywire/wiki/Automated-restart-of-node-app to try and lock down the manager app key but I cannot find the "ss" directory e.g.
`/usr/local/skywire/go/bin/.skywire/ss`
or
`~/.skywire/ss`

In both scenarios the permission of `.skywire` created is 0700.

I'm using this as a starting point to find where in the Manager the folder creation happens
