### ISSUE TITLE
Manager password restricted to maximum 20 characters (Low Priority)

### ISSUE THREAD

**Issue by BigOokie** [skycoin/skywire-testnet#99]
**LOW PRIORITY**
The Manager currently restricts the password to 20 characters currently. Given the password is hashed using BCRYPT, the maximum size of the password doesn't really matter as the resulting hash value will be the same size regardless of the length of the password.  Minimum password length check should continue to be enforced.

The following functions in `Monitor.go` contain these restrictions: `UpdatePass` and `Login`. Could reduce code by removing these as unsure they add value.

```
func (m *Monitor) Login(w http.ResponseWriter, r *http.Request) (result []byte, err error, code int) {
	...
	if len(pass) < 4 || len(pass) > 20 {...}

	err = checkPass(pass)
	...
}

func (m *Monitor) UpdatePass(w http.ResponseWriter, r *http.Request) (result []byte, err error, code int) {
	...
	if len(oldPass) < 4 || len(oldPass) > 20 {...}
	...
	if len(newPass) < 4 || len(newPass) > 20 {...}
	...
}
```

**Comment by gz-c** [comment]
TODO:

- Remove password restrictions (is a minimum even necessary?)
- Make sure the bcrypted password is also salted

**Comment by BigOokie** [comment]
> Remove password restrictions (is a minimum even necessary?)

Not wanting to complicate things - the default password is currently `1234`. On that basis, why not simply enforce a 4 character minimum. Technically I assume you would check that the password is at least 1 character (even if not enforcing password length) as a test to ensure there is a password or not.

**Comment by gz-c** [comment]
Yes would have to be at least 1 character.  I don't think it matters to us if a user wants to use a 1 character password
